declare module "betslip"
{
    import {ISelection} from "betslip-selection";
    import {IBetInfo} from "betslip-bet";
    import {IPurchase} from "betslip-purchase";

    /** State of betsip betting part */
    type BetsCollection = {
        /** List of selections in the betslip */
        selections: ISelection[];
        /** List of possbile bets */
        bets: IBetInfo[];
    }

    /** Betsip events */
    type BetslipEvent = "selectionUpdate" | "purchaseUpdated" | "cachoutUpdated";

    /** Information about the bet to be placed */
    type PlaceBetInformation = {
        /** bet id generated by server */
        betID : string,
        /** bet deposit in customer currency */
        deposit: number
    }

    /** Betslip API class */
    export interface IBetSlip
    {
        /** Adds new selection to the betslip
         *  @param selection selection id (from sports data API)
         *  @returns new betslip state promise
         */
        add(selection: string) : Promise<BetsCollection>;
        /** Removes selection from betslip
         * @param selection selection id 
         * @returns new betslip state promise
         */
        remove(selection: string) : Promise<BetsCollection>;

        /** Marks selection as part of combinator group
         * @param selection selection id
         * @param group combinator group id, empty to remove selection from the group
         * @returns new betslip state promise
         */
        setGroup(selection: string, group?: string): Promise<BetsCollection>;

        /** Manages selection state as the banker
         * @param selection selection id
         * @param banker mark or unmark selection as banker
         * @returns new betslip state promise
         */
        setBanker(selection: string, banker: boolean): Promise<BetsCollection>;

        /** Places the bet
         * @param bets information about the selected bets and deposits
         * @returns purchase promise
         */
        placeBets(bets: PlaceBetInformation[]): Promise<IPurchase>;

        /** Accepts new offer for the purchase 
         * @param purchaseid id of the purchase
         * @returns purchase promise
        */
        acceptOffer(purchaseid: string): Promise<IPurchase>;

        /** Declines new offer for the purchase 
         * @param purchaseid id of the purchase
         * @returns purchase in declined state promise 
        */
        declineOffer(purchaseid: string): Promise<IPurchase>;

        /** Event subscription
         * @param event name of the event
         * @param callback event callback
         */
        on(event: BetslipEvent, callback: (data: BetsCollection) => void);

        /** Event unsubscription
         * @param event name of the event
         * @param callback event callback
         */
        off(event: BetslipEvent, callback: (data: BetsCollection) => void)
    }
}